[build]
publish = "exampleSite/public"
command = "hugo -s DoubtAI"

[build.environment]
HUGO_VERSION       = ""
HUGO_THEME         = "DoubtAI"
HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_BASEURL = "https://doubt.ai"

[context.deploy-preview]
command = "hugo -s DoubtAI -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
command = "hugo -s DoubtAI -b $DEPLOY_PRIME_URL"
