[build]
publish = "DoubtAI/public"
command = "hugo -s DoubtAI"

[build.environment]
HUGO_VERSION       = ""
HUGO_THEME         = "DoubtAI"
HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_BASEURL = "https://doubt.ai"

[context.deploy-preview]
command = "hugo -s DoubtAI -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
command = "hugo -s DoubtAI -b $DEPLOY_PRIME_URL"

[build]
publish = "public"
command = "git submodule update --remote --merge && npm run build"

[context.production.environment]
HUGO_VERSION = "0.90.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "npm run build"

[context.split1.environment]
HUGO_VERSION = "0.90.0"
HUGO_ENV = "production"

[context.deploy-preview]
command = "npm run build"

[context.deploy-preview.environment]
HUGO_VERSION = "0.90.0"

[context.branch-deploy]
command = "npm run build"

[context.branch-deploy.environment]
HUGO_VERSION = "0.90.0"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"