name = "Doubt AI Site"
license = "No License"
licenselink = "https://github.com/DoubtAI/site"
description = "Doubt AI Marketing Site"

homepage = "https://doubt.ai"

tags = ["light", "simple", "blog", "clean", "tailwindcss", "responsive", "company", "modern", "slide"]
features = ["blog", "slides", "responsive"]

[author]
  name = "DoubtAI"
  homepage = "https://doubt.ai"
