baseURL = "https://doubt.ai/"
languageCode = "en-us"
title = "Doubt AI"
themesDir = "../.."
theme = "doubt-ai-theme"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.92.0"
    
[params]
#  google_analytics_id=""

  [params.logo]
    mobile = "images/logo-mobile.svg"
    mobile_height = "36px"
    mobile_width = "36px"
    desktop = "images/logo.svg"
    desktop_height = "29px"
    desktop_width = "217px"
    alt = "Hugo Hero"

  [params.homepage_meta_tags]
    meta_description = "Doubt AI"
    meta_og_title = "Doubt AI"
    meta_og_type = "website"
    meta_og_url = ""
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-hero-theme/master/images/tn.png"
    meta_og_description = "Doubt AI is as Security Project"
    meta_twitter_card = "summary"
    meta_twitter_site = "@DoubtAI"
    meta_twitter_creator = "@DoubtAI"

[[menu.main]]
	name = "Products"
	url = "/Produects/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "https://i.doubt.ai"
    weight = 2


[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 3

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
